[[plugins]]
repo = 'kana/vim-smartchr'
on_i = 1
hook_source = '''
  inoremap <buffer> <expr> = smartchr#loop(' = ', ' == ', '=')
  inoremap <buffer> <expr> + smartchr#loop(' + ', '++', '+')
  inoremap <buffer> <expr> - smartchr#loop(' - ', '--', '-')
'''

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
